package runtime_test

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/kyleking/wavez/internal/runtime"
)

// ollamaModelfile is the shape `ollama show --modelfile qwen3:8b` prints on
// this machine: a header whose comment repeats the model name as a FROM
// line, then the real blob path.
const ollamaModelfile = `# Modelfile generated by "ollama show"
# To build a new Modelfile based on this, replace FROM with:
# FROM qwen3:8b

FROM /Users/me/.ollama/models/blobs/sha256-a3de86cd
TEMPLATE """{{ .Prompt }}"""
`

func TestParseModelfileGGUF(t *testing.T) {
	t.Parallel()

	tests := []struct {
		wantErr error
		name    string
		out     string
		want    string
	}{
		{
			name: "ollama header comment is not the path",
			out:  ollamaModelfile,
			want: "/Users/me/.ollama/models/blobs/sha256-a3de86cd",
		},
		{
			name:    "base model reference is not a file",
			out:     "FROM llama3\n",
			wantErr: runtime.ErrNoGGUFPath,
		},
		{
			name:    "no FROM line",
			out:     "TEMPLATE \"\"\"{{ .Prompt }}\"\"\"\n",
			wantErr: runtime.ErrNoGGUFPath,
		},
		{
			name:    "empty",
			out:     "",
			wantErr: runtime.ErrNoGGUFPath,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got, err := runtime.ParseModelfileGGUF([]byte(tt.out))
			if tt.wantErr != nil {
				if !errors.Is(err, tt.wantErr) {
					t.Fatalf("ParseModelfileGGUF error = %v, want %v", err, tt.wantErr)
				}

				return
			}

			if err != nil {
				t.Fatalf("ParseModelfileGGUF: %v", err)
			}

			if got != tt.want {
				t.Errorf("ParseModelfileGGUF() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestVerifyGGUF(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		content string
		write   bool
		wantErr bool
	}{
		{name: "gguf magic", content: "GGUF\x03\x00\x00\x00", write: true, wantErr: false},
		{name: "wrong magic", content: "ollama-manifest", write: true, wantErr: true},
		{name: "shorter than the magic", content: "GG", write: true, wantErr: true},
		{name: "missing file", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			path := filepath.Join(t.TempDir(), "model.gguf")
			if tt.write {
				if err := os.WriteFile(path, []byte(tt.content), 0o600); err != nil {
					t.Fatalf("writing fixture: %v", err)
				}
			}

			err := runtime.VerifyGGUF(path)
			if (err != nil) != tt.wantErr {
				t.Fatalf("VerifyGGUF() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
