// Package sandbox generates a macOS Seatbelt profile and runs commands under
// it via sandbox-exec.
package sandbox

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/kyleking/wavez/internal/guard"
)

// Policy is what one profile allows beyond the floor every profile enforces.
// The zero value is the floor: nothing readable outside the project and the
// toolchain, and every loopback port reachable.
type Policy struct {
	// ReadDirs are directories outside the project root a command may read,
	// which is the project's own extraDirs. Reads are denied by default
	// across the home directory, so a sibling repository is unreadable until
	// the project names it.
	ReadDirs []string

	// LoopbackPorts are the loopback ports a command may reach. Empty leaves
	// every port reachable, which is what a project with no local model
	// configured gets.
	LoopbackPorts []int
}

// Profile is a rendered Seatbelt policy scoped to one project root and one
// session temp dir. Its paths are always realpath-resolved: /tmp, /var, and
// /etc are symlinks on macOS, and Seatbelt's subpath match is a literal
// prefix match against the resolved path, so an unresolved path silently
// denies everything under it. Build one with NewProfile, never by hand.
type Profile struct {
	projectRoot string
	sessionTmp  string
	home        string
	policy      Policy
}

// NewProfile resolves projectRoot and sessionTmp (and the current user's
// home dir) to their canonical, symlink-free form and returns a Profile
// scoped to them. Both directories must already exist. A ReadDir that does
// not resolve is dropped rather than failing the profile, since a project
// may name a sibling repository that is not checked out on this laptop.
func NewProfile(projectRoot, sessionTmp string, policy Policy) (*Profile, error) {
	root, err := realpath(projectRoot)
	if err != nil {
		return nil, fmt.Errorf("resolving project root: %w", err)
	}
	tmp, err := realpath(sessionTmp)
	if err != nil {
		return nil, fmt.Errorf("resolving session temp dir: %w", err)
	}
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("resolving home dir: %w", err)
	}
	home, err := realpath(homeDir)
	if err != nil {
		return nil, fmt.Errorf("resolving home dir: %w", err)
	}

	policy.ReadDirs = resolveAll(policy.ReadDirs)

	return &Profile{projectRoot: root, sessionTmp: tmp, home: home, policy: policy}, nil
}

// Render returns the profile's Seatbelt policy text.
func (p *Profile) Render() string {
	return RenderProfile(p.projectRoot, p.sessionTmp, p.home, p.policy)
}

// RenderProfile renders a Seatbelt policy for the given project root,
// session temp dir, and home dir, all of which must already be
// realpath-resolved. It is a pure function of its inputs: it touches
// neither the filesystem nor any external process, which is what makes it
// golden-testable without running sandbox-exec.
//
// Seatbelt takes the last matching rule, so each section here allows a
// region and then carves the exceptions out of it. Writes reach the project
// root and the session temp dir, minus the files that decide what a later
// command may run. Reads reach the project, the toolchain, and whatever the
// project named in extraDirs, and nothing else under the home directory.
// Network is loopback, narrowed to the ports the project's own models
// listen on when it names any.
func RenderProfile(projectRoot, sessionTmp, home string, policy Policy) string {
	var b strings.Builder
	b.WriteString("; Wavez v0.2 sandbox profile (macOS Seatbelt / sandbox-exec).\n")
	b.WriteString("; Generated by internal/sandbox; paths below are realpath-resolved.\n\n")
	b.WriteString("(version 1)\n")
	b.WriteString("(allow default)\n\n")

	writeSection(&b, projectRoot, sessionTmp)
	readSection(&b, projectRoot, sessionTmp, home, policy.ReadDirs)
	networkSection(&b, policy.LoopbackPorts)

	return b.String()
}

// writeSection scopes writes to the project root and the session temp dir,
// then denies the paths that grant permission to a later command. That deny
// is the whole guarantee: guard.ProtectedWrite classifies a command line and
// any interpreter defeats it, whereas this is checked by the kernel on the
// syscall no matter who made it.
func writeSection(b *strings.Builder, projectRoot, sessionTmp string) {
	b.WriteString("; --- writes: project root + session tmp only ---\n")
	b.WriteString("(deny file-write*)\n")
	b.WriteString("(allow file-write*\n")
	fmt.Fprintf(b, "  (subpath %s)\n", sbLiteral(projectRoot))
	fmt.Fprintf(b, "  (subpath %s)\n", sbLiteral(sessionTmp))
	b.WriteString("  (literal \"/dev/null\")\n")
	b.WriteString("  (literal \"/dev/tty\")\n")
	// Allocating a pty writes to the multiplexer and then to the slave the
	// kernel hands back, whose name is not known until it exists. Without
	// both, openpty(3) fails as "out of pty devices" and nothing a run
	// starts can drive a terminal program.
	b.WriteString("  (literal \"/dev/ptmx\")\n")
	b.WriteString("  (regex #\"^/dev/ttys[0-9]+$\"))\n\n")

	b.WriteString("; --- writes: not the files that decide what may run next ---\n")
	b.WriteString("(deny file-write*\n")
	for _, name := range guard.RepoInternals() {
		for _, leaf := range guard.RepoExecPaths() {
			fmt.Fprintf(b, "  (regex #\"%s\")\n", repoExecRegex(projectRoot, name, leaf))
		}
	}
	for _, rel := range guard.RootProtected() {
		fmt.Fprintf(b, "  (subpath %s)\n", sbLiteral(filepath.Join(projectRoot, rel)))
	}
	b.WriteString(")\n")
	// The session dir is wavez's own scratch and sits under the project root,
	// so the deny above reaches into it. uv marks its sdist cache with a file
	// literally named .git, which made every uv command in a sandboxed run
	// fail to open its cache.
	fmt.Fprintf(b, "(allow file-write* (subpath %s))\n\n", sbLiteral(sessionTmp))
}

// readSection inverts reads under the home directory: everything there is
// denied and the toolchain, the project, and the project's extraDirs are
// allowed back. Denying network is not what stops a leak, since anything a
// command prints enters the thread's context and the next hosted turn ships
// that context to the provider, so the read boundary is the confidentiality
// boundary and a denylist of nine credential paths was never one.
func readSection(b *strings.Builder, projectRoot, sessionTmp, home string, extra []string) {
	b.WriteString("; --- reads: the project and the toolchain, nothing else under home ---\n")
	fmt.Fprintf(b, "(deny file-read* (subpath %s))\n", sbLiteral(home))
	b.WriteString("(allow file-read*\n")

	allowed := append([]string{projectRoot, sessionTmp}, extra...)
	allowed = append(allowed, toolchainSubpaths(home)...)

	for _, dir := range dedupe(allowed) {
		fmt.Fprintf(b, "  (subpath %s)\n", sbLiteral(dir))
	}

	// A directory's ancestors are readable as themselves and not as
	// subpaths, so a tool walking upward can stat and list each parent
	// without any file under it becoming readable. pytest does exactly this
	// looking for its rootdir, and dies with a bare PermissionError naming
	// the ancestor when it cannot.
	for _, dir := range ancestorsWithin(home, dedupe(allowed)) {
		fmt.Fprintf(b, "  (literal %s)\n", sbLiteral(dir))
	}

	for _, file := range toolchainFiles(home) {
		fmt.Fprintf(b, "  (literal %s)\n", sbLiteral(file))
	}

	b.WriteString(")\n\n")
}

func networkSection(b *strings.Builder, ports []int) {
	b.WriteString("; --- network: loopback only ---\n")
	b.WriteString("(deny network*)\n")

	if len(ports) == 0 {
		b.WriteString("(allow network-outbound (remote ip \"localhost:*\"))\n")
		b.WriteString("(allow network-inbound (local ip \"localhost:*\"))\n")

		return
	}

	// A local proxy is an outbound path, so a project that names the ports
	// its own models listen on gets those and not every service on the
	// laptop.
	b.WriteString("(allow network-outbound\n")
	for _, port := range dedupeInts(ports) {
		fmt.Fprintf(b, "  (remote ip %s)\n", sbLiteral("localhost:"+strconv.Itoa(port)))
	}
	b.WriteString(")\n")
}

// toolchainSubpaths are the directories under home a build reads from. Each
// is a cache or an installed toolchain rather than anything the user wrote,
// so allowing them back after the home-wide deny costs no confidentiality
// and is the difference between a build that runs and one that cannot find
// its compiler.
func toolchainSubpaths(home string) []string {
	names := []string{
		".bun", ".cache", ".cargo", ".config/jj", ".config/mise", ".deno", ".dotnet",
		".gradle", ".local", ".m2", ".npm", ".nvm", ".pyenv", ".rbenv", ".rustup",
		".config/git", ".sdkman", "Library/Application Support/jj", "Library/Caches",
		"Library/pnpm", "go",
	}
	out := make([]string, 0, len(names))

	for _, name := range names {
		out = append(out, filepath.Join(home, filepath.FromSlash(name)))
	}

	return out
}

// toolchainFiles are the individual files under home a toolchain reads:
// git's global config, and the ignore file it conventionally points
// `core.excludesFile` at. Without them a sandboxed `jj st` cannot see the
// user's global ignore rules, and since jj snapshots on every command it
// adds the files those rules excluded to the working copy. They are named as
// literals rather than a subpath so `.gitconfig` does not also admit
// whatever sits beside it.
func toolchainFiles(home string) []string {
	return []string{
		filepath.Join(home, ".gitconfig"),
		filepath.Join(home, ".gitignore_global"),
	}
}

// ancestorsWithin lists every directory between home and each of dirs,
// home included, so an upward walk can see each level without reading into
// it. A dir outside home contributes nothing, since reads there are not
// denied in the first place.
func ancestorsWithin(home string, dirs []string) []string {
	seen := map[string]bool{}
	out := []string{}

	for _, dir := range dirs {
		for cur := filepath.Dir(dir); strings.HasPrefix(cur, home); cur = filepath.Dir(cur) {
			if !seen[cur] {
				seen[cur] = true

				out = append(out, cur)
			}

			// filepath.Dir of a root path is itself, so an unrooted input
			// would spin here forever rather than reaching home.
			if cur == filepath.Dir(cur) {
				break
			}
		}
	}

	sort.Strings(out)

	return out
}

// repoExecRegex matches leaf at any depth inside a version-control directory
// named dir, itself at any depth below root, which is how a nested checkout's
// hooks are covered the same as the project's own. `config` also matches
// git's `config.worktree`, which carries the same setting.
//
// It stays anchored to the root because the directory name is not reserved
// outside one: uv marks its sdist cache with a file literally named .git, and
// an unanchored rule made every uv command in a sandboxed run fail to open
// its cache.
func repoExecRegex(root, dir, leaf string) string {
	return "^" + quoteRegex(root) + "(/.*)?/" + quoteRegex(dir) + "(/.*)?/" + quoteRegex(leaf) + "($|/|\\.)"
}

// quoteRegex escapes the characters Seatbelt's regex syntax reads specially,
// so a path becomes a literal match.
func quoteRegex(s string) string {
	var b strings.Builder

	for _, r := range s {
		if strings.ContainsRune(`\.+*?()|[]{}^$`, r) {
			b.WriteByte('\\')
		}

		b.WriteRune(r)
	}

	return b.String()
}

func dedupe(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))

	for _, s := range in {
		if s == "" || seen[s] {
			continue
		}

		seen[s] = true

		out = append(out, s)
	}

	sort.Strings(out)

	return out
}

func dedupeInts(in []int) []int {
	seen := map[int]bool{}
	out := make([]int, 0, len(in))

	for _, n := range in {
		if seen[n] {
			continue
		}

		seen[n] = true

		out = append(out, n)
	}

	sort.Ints(out)

	return out
}

func resolveAll(dirs []string) []string {
	out := make([]string, 0, len(dirs))

	for _, dir := range dirs {
		resolved, err := realpath(dir)
		if err != nil {
			continue
		}

		out = append(out, resolved)
	}

	return out
}

func sbLiteral(path string) string {
	escaped := strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(path)

	return `"` + escaped + `"`
}

func realpath(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("making %q absolute: %w", path, err)
	}
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return "", fmt.Errorf("resolving symlinks in %q: %w", abs, err)
	}

	return resolved, nil
}
