// Package sandbox generates a macOS Seatbelt profile and runs commands under
// it via sandbox-exec.
package sandbox

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Profile is a rendered Seatbelt policy scoped to one project root and one
// session temp dir. Its paths are always realpath-resolved: /tmp, /var, and
// /etc are symlinks on macOS, and Seatbelt's subpath match is a literal
// prefix match against the resolved path, so an unresolved path silently
// denies everything under it. Build one with NewProfile, never by hand.
type Profile struct {
	projectRoot string
	sessionTmp  string
	home        string
}

// NewProfile resolves projectRoot and sessionTmp (and the current user's
// home dir) to their canonical, symlink-free form and returns a Profile
// scoped to them. Both directories must already exist.
func NewProfile(projectRoot, sessionTmp string) (*Profile, error) {
	root, err := realpath(projectRoot)
	if err != nil {
		return nil, fmt.Errorf("resolving project root: %w", err)
	}
	tmp, err := realpath(sessionTmp)
	if err != nil {
		return nil, fmt.Errorf("resolving session temp dir: %w", err)
	}
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("resolving home dir: %w", err)
	}
	home, err := realpath(homeDir)
	if err != nil {
		return nil, fmt.Errorf("resolving home dir: %w", err)
	}

	return &Profile{projectRoot: root, sessionTmp: tmp, home: home}, nil
}

// Render returns the profile's Seatbelt policy text.
func (p *Profile) Render() string {
	return RenderProfile(p.projectRoot, p.sessionTmp, p.home)
}

// RenderProfile renders a Seatbelt policy for the given project root,
// session temp dir, and home dir, all of which must already be
// realpath-resolved. It is a pure function of its inputs: it touches
// neither the filesystem nor any external process, which is what makes it
// golden-testable without running sandbox-exec.
//
// Writes are scoped to projectRoot and sessionTmp. Reads of ~/.ssh, ~/.aws,
// ~/.config/gh, ~/Library/Keychains, and ~/.claude under home are denied.
// /dev/null and /dev/tty are allowed explicitly (git needs the former even
// under a deny-by-default write policy). Network is loopback-only.
func RenderProfile(projectRoot, sessionTmp, home string) string {
	var b strings.Builder
	b.WriteString("; Wavez v0.1 sandbox profile (macOS Seatbelt / sandbox-exec).\n")
	b.WriteString("; Generated by internal/sandbox; paths below are realpath-resolved.\n\n")
	b.WriteString("(version 1)\n")
	b.WriteString("(allow default)\n\n")

	b.WriteString("; --- writes: project root + session tmp only ---\n")
	b.WriteString("(deny file-write*)\n")
	b.WriteString("(allow file-write*\n")
	fmt.Fprintf(&b, "  (subpath %s)\n", sbLiteral(projectRoot))
	fmt.Fprintf(&b, "  (subpath %s)\n", sbLiteral(sessionTmp))
	b.WriteString("  (literal \"/dev/null\")\n")
	b.WriteString("  (literal \"/dev/tty\"))\n\n")

	b.WriteString("; --- reads: everything except secrets ---\n")
	b.WriteString("(deny file-read*\n")
	for _, secret := range secretSubpaths(home) {
		fmt.Fprintf(&b, "  (subpath %s)\n", sbLiteral(secret))
	}
	b.WriteString(")\n\n")

	b.WriteString("; --- network: loopback only ---\n")
	b.WriteString("(deny network*)\n")
	b.WriteString("(allow network-outbound (remote ip \"localhost:*\"))\n")
	b.WriteString("(allow network-inbound (local ip \"localhost:*\"))\n")

	return b.String()
}

func secretSubpaths(home string) []string {
	return []string{
		filepath.Join(home, ".ssh"),
		filepath.Join(home, ".aws"),
		filepath.Join(home, ".config", "gh"),
		filepath.Join(home, "Library", "Keychains"),
		filepath.Join(home, ".claude"),
	}
}

func sbLiteral(path string) string {
	escaped := strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(path)
	return `"` + escaped + `"`
}

func realpath(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("making %q absolute: %w", path, err)
	}
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return "", fmt.Errorf("resolving symlinks in %q: %w", abs, err)
	}

	return resolved, nil
}
