package app

import (
	"context"
	"strings"

	"github.com/kyleking/wavez/internal/agent"
	"github.com/kyleking/wavez/internal/finish"
	"github.com/kyleking/wavez/internal/llm"
	"github.com/kyleking/wavez/internal/tool"
)

// FinishChecker runs every deterministic finish check over a completed run.
// It is what DESIGN.md's item 16 replaces the model reviewer with: four
// bounds, each able to fail a run on its own, and none of them a claim that
// the diff is correct.
type FinishChecker struct {
	index    finish.Index
	cov      finish.Coverage
	differ   Differ
	written  Written
	opened   finish.Opened
	root     string
	fixtures []string
}

// Written names every file the run changed, whoever wrote it. The change
// set the edit tools record holds only what they wrote, and a golden
// fixture is regenerated by a test command through the shell, so the only
// place that rewrite shows up is version control.
type Written interface {
	ChangedFiles(ctx context.Context, repoRoot, marker string) ([]string, error)
}

// NewFinishChecker builds a checker rooted at root. A nil index or coverage
// map makes the checks that need it abstain rather than fail, since a
// workspace that never built one would otherwise fail every run for the
// workspace's reason.
func NewFinishChecker(
	root string, index finish.Index, cov finish.Coverage, differ Differ, opened finish.Opened,
	written Written, fixtures []string,
) *FinishChecker {
	return &FinishChecker{
		root: root, index: index, cov: cov, differ: differ, opened: opened,
		written: written, fixtures: fixtures,
	}
}

// Check implements agent.Finisher.
func (c *FinishChecker) Check(ctx context.Context, f agent.Finish) ([]string, error) {
	changed := paths(f.Changes)

	var reports []finish.Report

	named, err := finish.NamedThingsExist(ctx, c.root, f.Answer, c.index, changed, transcript(f.History))
	if err != nil {
		return nil, err //nolint:wrapcheck // the check already names the lookup that failed
	}

	reports = append(reports, named)

	task, err := finish.ChangeSetMatchesTask(c.root, f.Task, changed)
	if err != nil {
		return nil, err //nolint:wrapcheck // the check already names the file that failed
	}

	reports = append(reports, task)

	if f.Goal != "" && f.Goal != f.Task {
		goal, gerr := finish.ChangeSetMatchesGoal(c.root, f.Goal, changed)
		if gerr != nil {
			return nil, gerr //nolint:wrapcheck // the check already names the file that failed
		}

		reports = append(reports, goal)
	}

	tested, err := finish.ChangedLinesAreTested(ctx, f.Changes, c.cov)
	if err != nil {
		return nil, err //nolint:wrapcheck // the check already names the file that failed
	}

	reports = append(reports, tested, c.substance(ctx, f, changed),
		finish.AnswerReadsWhatItNames(c.root, f.Answer, changed, c.opened),
		finish.FixturesAreAccountedFor(f.Answer, c.wrote(ctx, f, changed), c.fixtures))

	return findings(reports), nil
}

// wrote is every path the run changed. An empty checkpoint makes jj diff
// from the root commit, where every tracked file reads as changed, so the
// edit tools' own change set answers instead.
func (c *FinishChecker) wrote(ctx context.Context, f agent.Finish, changed []string) []string {
	if c.written == nil || f.Checkpoint == "" {
		return changed
	}

	paths, err := c.written.ChangedFiles(ctx, c.root, f.Checkpoint)
	if err != nil {
		return changed
	}

	return paths
}

// substance reads what the run actually wrote. A diff that cannot be
// produced abstains: this bound exists to catch a run that did nothing, and
// failing one because version control was unavailable would say something
// about the machine instead.
func (c *FinishChecker) substance(ctx context.Context, f agent.Finish, changed []string) finish.Report {
	if c.differ == nil || f.Checkpoint == "" || len(changed) == 0 {
		return finish.Report{}
	}

	diff, err := c.differ.Diff(ctx, c.root, f.Checkpoint, changed)
	if err != nil {
		return finish.Report{}
	}

	return finish.ChangeHasSubstance(diff)
}

// transcript is every word the run was sent or produced, which is what
// grounds a name the closing answer quotes.
func transcript(history []llm.Message) string {
	var b strings.Builder

	for _, msg := range history {
		b.WriteString(msg.Content)
		b.WriteByte('\n')

		for _, part := range msg.Parts {
			if part.Kind == llm.PartText {
				b.WriteString(part.Text)
				b.WriteByte('\n')
			}
		}

		for _, call := range msg.ToolCalls {
			b.Write(call.Input)
			b.WriteByte('\n')
		}
	}

	return b.String()
}

func findings(reports []finish.Report) []string {
	var out []string

	for _, r := range reports {
		for _, f := range r.Findings {
			out = append(out, f.Check+": "+f.Detail)
		}
	}

	return out
}

func paths(changes []tool.Change) []string {
	seen := make(map[string]bool, len(changes))
	out := make([]string, 0, len(changes))

	for _, c := range changes {
		if seen[c.Path] {
			continue
		}

		seen[c.Path] = true

		out = append(out, c.Path)
	}

	return out
}
