package app_test

import (
	"context"
	"strings"
	"testing"

	"github.com/kyleking/wavez/internal/agent"
	"github.com/kyleking/wavez/internal/app"
	"github.com/kyleking/wavez/internal/tool"
)

// stubWritten is version control's answer about what the run changed.
type stubWritten struct{ paths []string }

func (s stubWritten) ChangedFiles(context.Context, string, string) ([]string, error) {
	return s.paths, nil
}

// The other bounds abstain on a nil index, coverage map, differ, and scope,
// which is what leaves the fixture bound as the one thing under test here.
func TestFinishCheckerReportsAnUnmentionedFixture(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	// The edit tools wrote the source file; the snapshot was regenerated by a
	// test command through the shell, which is why only version control has
	// it and why the bound would see nothing without that answer.
	changes := []tool.Change{{Path: "src/ui/screen.py"}}
	tracked := []string{"src/ui/screen.py", "tests/__snapshots__/main.raw"}

	tests := []struct {
		written app.Written
		name    string
		answer  string
		wantHit bool
	}{
		{
			name:    "silence about a fixture only version control saw",
			answer:  "Moved the input. Tests pass.",
			written: stubWritten{paths: tracked},
			wantHit: true,
		},
		{
			name:    "the answer names it",
			answer:  "Regenerated main.raw after reading the frames.",
			written: stubWritten{paths: tracked},
		},
		{
			name:   "without version control only the edit tools' own set is read",
			answer: "Moved the input. Tests pass.",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			checker := app.NewFinishChecker(root, nil, nil, nil, nil, tt.written,
				[]string{"**/__snapshots__/**"})

			findings, err := checker.Check(t.Context(), agent.Finish{
				Task: "move the input", Answer: tt.answer, Changes: changes, Checkpoint: "op1",
			})
			if err != nil {
				t.Fatalf("Check: %v", err)
			}

			var got bool

			for _, f := range findings {
				if strings.Contains(f, "golden fixture") {
					got = true
				}
			}

			if got != tt.wantHit {
				t.Errorf("fixture finding = %v, want %v (findings=%v)", got, tt.wantHit, findings)
			}
		})
	}
}
